### PR TITLE
Noarch version of this package

### PR DESCRIPTION
**Pull request by mpharrigan**
This is an example of what it would look like to have just a dumb archive. Programs that consume this data (msmbuilder) would be responsible for finding the files and loading them

``` python
import mdtraj
import sys
files = glob.glob("{}/share/msmb_data/alanine_dipeptide/trajectories-*.???".format(sys.prefix))
```

### CODE REVIEW

**Comment by mpharrigan** [comment]
3abcdd9 should be backported anyhow

**Comment by mpharrigan** [comment]
I generally like this idea because it fixes #10 / we only need one package.

It's super-decoupled from msmbuilder ... any project can easily download this data

**Comment by mpharrigan** [comment]
regarding the muller data and 1d wells: we should generate a fixed dataset from those (e.g. using random state 0) and keep the python code in msmbuilder

**Comment by cxhernandez** [comment]
I'm unclear as to what the advantage the 'dumb' archive has over using convenience functions like `fetch_alanine_dipeptide`. It's nice to be able to `conda install` and just use those functions rather than worry about where the data lives

**Comment by mpharrigan** [comment]
`fetch_alanine_dipeptide` would continue to live in msmbuilder

**Comment by cxhernandez** [comment]
> fetch_alanine_dipeptide would continue to live in msmbuilder

I'm -1 on this. At the very least could we provide a function that makes it easy to get the path to each dataset?

**Comment by mpharrigan** [comment]
I don't think it's unreasonable to have to use msmbuilder to load files contained in a package called `msmb_data`. Having a method to return a path would be easier for people who don't have msmbuilder installed at the cost of having to host 3 copies of these 400mib of data AND for conda to cache a copy for each version of python you have installed in different envs. 

I see it this way. These datasets are part of msmbuilder, but they're too big to include by default. Esp since not everyone wants them. Up to now, we shipped msmbuilder python code that lazily caches this data to `~/msmbuilder_data/` when it's needed. Now, the design is pretty identical but the missing puzzle piece would be the `msmb_data` conda package and the path is now in `share/msmbuilder_data` (note that this is the purpose of the share directory in the linux FHS standard)

If you want a python package that gives you sample molecular dynamics data, that could be well served by a small python package that also depends on `msmb_data` conda archive. In fact, having this be a noarch conda package means it could also be used (or wrapped) by R packages, c++ code, et al.

But this should be considered a part of msmbuilder, and the only reason why it's not `package_data` in msmbuilder's setup.py is for purely practical considerations

**Comment by cxhernandez** [comment]
> Having a method to return a path would be easier for people who don't have msmbuilder installed at the cost of having to host 3 copies of these 400mib of data AND for conda to cache a copy for each version of python you have installed in different envs.

Alright fineeeee

**Comment by mpharrigan** [comment]
(rebased)

**Comment by mpharrigan** [comment]
lol tried to make the windows install batch file. I always wonder if copy utilities will see the destination as the destination name or the directory into which it should put stuff. Didn't know how windows would handle this. Turns out, it stops and asks

> Does C:\users\mph\Miniconda3\envs\_build\share\msmb_data specify a file name or directory name on the target?
> (F = file, D = directory)? _

**Pull request merged**
